using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EventMapper.SourceGenerators.ExtensionMethods;

public static class EventMapperBuilderExtensions
{
    extension(SourceProductionContext context)
    {
        internal void BuildMapperSourceFiles(GeneratedEventMapperData mapperData)
        {
            context.LogOnBuild($"AUTOGEN ----- Generating EventMapper for: {mapperData.EventTypeName}");

            StringBuilder sb = new();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            // sb.AppendWarningDisables();

            sb.AppendLine($"using {mapperData.EventNamespace};");
            sb.AppendLine($"namespace {EventMappingProfile.MapperNamespace};");

            // Start class
            sb.AppendLine($"public static partial class {EventMappingProfile.MapperClassName}");
            sb.AppendLine("{");

            sb.AppendToDomainEvent(mapperData);
            sb.AppendToDatabaseEvent(mapperData);

            // End class
            sb.AppendLine("}");
            // sb.AppendWarningRestores();

            context.AddSource($"{mapperData.EventTypeName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            sb.Clear();
        }

        private void LogOnBuild(string message, bool asInfo = false)
        {
            context.ReportDiagnostic(
                    Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "EVENT_MAPPER_GENERATOR_0001",
                            "Debug",
                            message,
                            "EventMapperGenerator",
                            asInfo ? DiagnosticSeverity.Info : DiagnosticSeverity.Warning,
                            isEnabledByDefault: true
                        ),
                        Location.None,
                        asInfo ? "Info" : "Warning")
                    );
        }

    }

    extension(StringBuilder sb)
    {
        internal void AppendToDomainEvent(GeneratedEventMapperData mapperData)
        {
        }

        internal void AppendToDatabaseEvent(GeneratedEventMapperData mapperData)
        {
        }

    }
}
