using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EventMapper.SourceGenerators.ExtensionMethods;

public static class EventMapperBuilderExtensions
{
    extension(SourceProductionContext context)
    {
        internal void BuildMapperSourceFile(GeneratedEventMapperData mapperData)
        {
            context.LogOnBuild($"AUTOGEN ----- Generating EventMapper for: {mapperData.EventTypeName}");

            StringBuilder sb = new();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");

            sb.AppendLine($"using {mapperData.EventNamespace};");
            sb.AppendLine("using using System.Text.Json;");
            sb.AppendLine("using using System.Text.Json.Nodes;");
            sb.AppendLine($"namespace {EventMappingProfile.MapperNamespace};");

            // Start class
            sb.AppendLine($"public static partial class {EventMappingProfile.MapperClassName}");
            sb.AppendLine("{");

            sb.AppendToDomainEvent(mapperData);
            sb.AppendToPayload(mapperData);

            // End class
            sb.AppendLine("}");

            context.AddSource(
                    $"{mapperData.EventTypeName}.{EventMappingProfile.MapperClassName}.g.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8)
                    );
            sb.Clear();
        }

        private void LogOnBuild(string message, bool asInfo = false)
        {
            context.ReportDiagnostic(
                    Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "EVENT_MAPPER_GENERATOR_0001",
                            "Debug",
                            message,
                            "EventMapperGenerator",
                            asInfo ? DiagnosticSeverity.Info : DiagnosticSeverity.Warning,
                            isEnabledByDefault: true
                        ),
                        Location.None,
                        asInfo ? "Info" : "Warning")
                    );
        }

    }

    extension(StringBuilder sb)
    {
        internal void AppendToDomainEvent(GeneratedEventMapperData mapperData)
        {
            sb.AppendLine($"\tpublic static {mapperData.EventTypeName} FromDbEventTo{mapperData.EventTypeName}({EventMappingProfile.DbEventType.FullName} dbEvent)");
            sb.AppendLine($"\t\t=> new {mapperData.EventTypeName}(");

            var args = new List<string>();
            foreach (var prop in mapperData.BaseProps)
            {
                args.Add($"\t\t\t{prop.Name}: dbEvent.{prop.Name}");
            }

            foreach (var prop in mapperData.PayloadProps)
            {
                args.Add($"\t\t\t{prop.Name}: JsonSerializer.Deserialize<{prop.Type.Name}>(dbEvent.{prop.Name})!");
            }

            sb.AppendJoin(",\n", args).AppendLine();

            sb.AppendLine("\t);");
        }

        internal void AppendToPayload(GeneratedEventMapperData mapperData)
        {
            sb.AppendLine($"\tpublic static string ToPayload({mapperData.EventTypeName} e)");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tvar json = new JsonObject();");
            foreach (var prop in mapperData.PayloadProps)
            {
                sb.AppendLine($"\t\tjson[\"{prop.Name}\"] = JsonSerializer.SerializeToNode(e.{prop.Name});");
            }
            sb.AppendLine("\t\treturn json.ToString();");
            sb.AppendLine("\t}");
        }

    }
}
