using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DtoGenerator;

public static class DtoBuilderExtensions
{
    public static void BuildDtoSourceFiles(this SourceProductionContext context,
            GeneratedDtoData dtoData)
    {
        context.LogOnBuild($"AUTOGEN ----- Generating Dto: {dtoData.DtoName}");

        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        // Add target namespace
        sb.AppendLine($"namespace {dtoData.TargetNamespace};");

        // Start class
        sb.AppendLine($"public partial class {dtoData.DtoName}");
        sb.AppendLine("{");

        sb.AppendProps(dtoData);
        sb.AppendFromMethod(dtoData);

        // Add closing braces
        sb.AppendLine("}");

        context.AddSource($"{dtoData.DtoName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        sb.Clear();
    }


    private static void AppendProps(this StringBuilder sb,
            GeneratedDtoData dtoData)
    {
        foreach (var property in dtoData.Properties)
        {
            string type = property.Type.ToFullString();
            string identifier = property.Identifier.ValueText;

            sb.AppendLine($"\t{$"public {type} {identifier} {{get; set;}}"}");
        }
    }


    private static void AppendFromMethod(this StringBuilder sb,
            GeneratedDtoData dtoData)
    {
        sb.AppendLine($"\tpublic static {dtoData.DtoName} From({dtoData.TargetName} entity)");
        sb.AppendLine("\t{");
        sb.AppendLine($"\t\treturn new {dtoData.DtoName} {{");
        foreach (var property in dtoData.Properties)
        {
            string identifier = property.Identifier.ValueText;
            sb.AppendLine($"\t\t\t{identifier} = entity.{identifier},");
        }
        sb.AppendLine("\t\t};");
        sb.AppendLine("\t}");

    }

    private static void LogOnBuild(this SourceProductionContext context,
            string message,
            bool asInfo = false)
    {
        context.ReportDiagnostic(
                Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "DTOGEN002",
                        "Debug",
                        message,
                        "DtoGenerator",
                        asInfo ? DiagnosticSeverity.Info : DiagnosticSeverity.Warning,
                        isEnabledByDefault: true
                    ),
                    Location.None,
                    asInfo ? "Info" : "Warning")
                );
    }

}

