using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DtoGenerator;

public static class DtoBuilderExtensions
{
    public static void BuildDtoSourceFiles(this SourceProductionContext context,
            GeneratedDtoData dtoData)
    {
        context.LogOnBuild($"AUTOGEN ----- Generating Dto: {dtoData.DtoName}");

        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        // Add usings
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");

        // Add target namespace
        sb.AppendLine($"namespace {dtoData.TargetNamespace};");

        // Start class
        sb.AppendLine($"public partial class {dtoData.DtoName}");
        sb.AppendLine("{");

        // for each property in the domain entity, create a corresponding property 
        // in the DTO with the same type
        foreach (var property in dtoData.Properties)
        {
            string type = property.Type.ToFullString();
            string identifier = property.Identifier.ValueText;

            sb.AppendLine($"\t{$"public {type} {identifier} {{get; set;}}"}");
        }

        // Add closing braces
        sb.AppendLine("}");

        context.AddSource($"{dtoData.DtoName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        sb.Clear();
    }


    public static void LogOnBuild(this SourceProductionContext context,
            string message,
            bool asInfo = false)
    {
        context.ReportDiagnostic(
                Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "DTOGEN002",
                        "Debug",
                        message,
                        "DtoGenerator",
                        asInfo ? DiagnosticSeverity.Info : DiagnosticSeverity.Warning,
                        isEnabledByDefault: true
                    ),
                    Location.None,
                    asInfo ? "Info" : "Warning")
                );

    }

}

