// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(EntitiesContext))]
    [Migration("20260205185321_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Domain.Entities.Schedules.ChecklistState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Checklists");
                });

            modelBuilder.Entity("Domain.Entities.Schedules.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.ToTable("TaskEntity");
                });

            modelBuilder.Entity("Domain.Entities.Users.UserState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.Schedules.ChecklistState", b =>
                {
                    b.HasOne("Domain.Entities.Users.UserState", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Schedules.ChecklistState", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Entities.Schedules.ValueObjects.Statistics", "Statistics", b1 =>
                        {
                            b1.Property<Guid>("ChecklistStateId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("TEXT");

                            b1.HasKey("ChecklistStateId");

                            b1.ToTable("Checklists");

                            b1.WithOwner()
                                .HasForeignKey("ChecklistStateId");

                            b1.OwnsOne("Domain.Entities.Schedules.ValueObjects.Rating", "LLMRating", b2 =>
                                {
                                    b2.Property<Guid>("StatisticsChecklistStateId")
                                        .HasColumnType("TEXT");

                                    b2.Property<byte>("EffortRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("LLM_EffortRating");

                                    b2.Property<byte>("FocusRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("LLM_FocusRating");

                                    b2.Property<byte>("MoodRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("LLM_MoodRating");

                                    b2.Property<byte>("MotivationRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("LLM_MotivationRating");

                                    b2.Property<byte>("ProductivityRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("LLM_ProductivityRating");

                                    b2.Property<byte>("StressRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("LLM_StressRating");

                                    b2.HasKey("StatisticsChecklistStateId");

                                    b2.ToTable("Checklists");

                                    b2.WithOwner()
                                        .HasForeignKey("StatisticsChecklistStateId");
                                });

                            b1.OwnsOne("Domain.Entities.Schedules.ValueObjects.Rating", "UserRating", b2 =>
                                {
                                    b2.Property<Guid>("StatisticsChecklistStateId")
                                        .HasColumnType("TEXT");

                                    b2.Property<byte>("EffortRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("User_EffortRating");

                                    b2.Property<byte>("FocusRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("User_FocusRating");

                                    b2.Property<byte>("MoodRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("User_MoodRating");

                                    b2.Property<byte>("MotivationRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("User_MotivationRating");

                                    b2.Property<byte>("ProductivityRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("User_ProductivityRating");

                                    b2.Property<byte>("StressRating")
                                        .HasColumnType("INTEGER")
                                        .HasColumnName("User_StressRating");

                                    b2.HasKey("StatisticsChecklistStateId");

                                    b2.ToTable("Checklists");

                                    b2.WithOwner()
                                        .HasForeignKey("StatisticsChecklistStateId");
                                });

                            b1.Navigation("LLMRating");

                            b1.Navigation("UserRating");
                        });

                    b.Navigation("Statistics")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Schedules.TaskEntity", b =>
                {
                    b.HasOne("Domain.Entities.Schedules.ChecklistState", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.Entities.Schedules.ValueObjects.Schedule", "ActualSchedule", b1 =>
                        {
                            b1.Property<Guid>("TaskEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("ActualSchedule_End");

                            b1.Property<DateTimeOffset>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("ActualSchedule_Start");

                            b1.HasKey("TaskEntityId");

                            b1.ToTable("TaskEntity");

                            b1.WithOwner()
                                .HasForeignKey("TaskEntityId");
                        });

                    b.OwnsOne("Domain.Common.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("TaskEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("TaskEntityId");

                            b1.ToTable("TaskEntity");

                            b1.WithOwner()
                                .HasForeignKey("TaskEntityId");
                        });

                    b.OwnsOne("Domain.Entities.Schedules.ValueObjects.Schedule", "PlannedSchedule", b1 =>
                        {
                            b1.Property<Guid>("TaskEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PlannedSchedule_End");

                            b1.Property<DateTimeOffset>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("PlannedSchedule_Start");

                            b1.HasKey("TaskEntityId");

                            b1.ToTable("TaskEntity");

                            b1.WithOwner()
                                .HasForeignKey("TaskEntityId");
                        });

                    b.OwnsOne("Domain.Entities.Schedules.ValueObjects.TaskType", "TaskType", b1 =>
                        {
                            b1.Property<Guid>("TaskEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Category")
                                .HasColumnType("INTEGER")
                                .HasColumnName("TaskType_Category");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("TaskType_Name");

                            b1.HasKey("TaskEntityId");

                            b1.ToTable("TaskEntity");

                            b1.WithOwner()
                                .HasForeignKey("TaskEntityId");
                        });

                    b.Navigation("ActualSchedule");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PlannedSchedule")
                        .IsRequired();

                    b.Navigation("TaskType")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Users.UserState", b =>
                {
                    b.OwnsOne("Domain.Common.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserStateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("UserStateId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserStateId");
                        });

                    b.OwnsOne("Domain.Entities.Users.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("UserStateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("UserStateId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserStateId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PasswordHash")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Schedules.ChecklistState", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
