using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DtoGenerator.SourceGenerators.ExtensionMethods;

internal static class DtoBuilderExtensions
{
    private static readonly SymbolDisplayFormat TypeFormat = SymbolDisplayFormat.FullyQualifiedFormat
        .AddGenericsOptions(SymbolDisplayGenericsOptions.IncludeTypeParameters);

    extension(SourceProductionContext context)
    {
        public void BuildDtoSourceFiles(GeneratedDtoData dtoData)
        {
            context.LogOnBuild($"AUTOGEN ----- Generating Dto: {dtoData.DtoName}");

            StringBuilder sb = new();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendWarningDisables();

            sb.AppendLine($"using {dtoData.TargetNamespace};");
            sb.AppendLine($"namespace {dtoData.DtoNamespace};");

            // Start class
            sb.AppendLine($"public partial class {dtoData.DtoName}");
            sb.AppendLine("{");

            sb.AppendProps(dtoData);
            sb.AppendFromMethod(dtoData);

            // End class
            sb.AppendLine("}");
            sb.AppendWarningRestores();

            context.AddSource($"{dtoData.DtoName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            sb.Clear();
        }


        private void LogOnBuild(string message, bool asInfo = false)
        {
            context.ReportDiagnostic(
                    Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "DTOGEN001",
                            "Debug",
                            message,
                            "DtoGenerator",
                            asInfo ? DiagnosticSeverity.Info : DiagnosticSeverity.Warning,
                            isEnabledByDefault: true
                        ),
                        Location.None,
                        asInfo ? "Info" : "Warning")
                    );
        }
    }


    extension(StringBuilder sb)
    {
        private void AppendProps(GeneratedDtoData dtoData)
        {
            foreach (var property in dtoData.Properties)
            {
                string type = GetTypeName(property.Type);
                string identifier = property.Name;

                if (dtoData.PropNameToMappedType.TryGetValue(identifier, out var mappedType))
                {
                    if (IsCollectionType(property))
                    {
                        type = $"global::System.Collections.Generic.List<{mappedType}>";
                    }
                    else
                    {
                        type = mappedType;
                    }
                }

                sb.AppendLine($"\tpublic {type} {identifier} {{get; set;}}");
            }
        }


        private void AppendFromMethod(GeneratedDtoData dtoData)
        {
            sb.AppendLine($"\tpublic static {dtoData.DtoName} From({dtoData.TargetName} entity)");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tif (entity is null) return null;");
            sb.AppendLine($"\t\treturn new {dtoData.DtoName} {{");
            foreach (var property in dtoData.Properties)
            {
                string identifier = property.Name;
                bool isCollection = IsCollectionType(property);

                if (dtoData.PropNameToMappedType.TryGetValue(identifier, out var mappedType))
                {
                    if (isCollection)
                    {
                        sb.AppendLine($"\t\t\t{identifier} = entity.{identifier}?.Select(x => {mappedType}.From(x!)).ToList(),");
                    }
                    else
                    {
                        sb.AppendLine($"\t\t\t{identifier} = {mappedType}.From(entity.{identifier}),");
                    }
                }
                else
                {
                    if (isCollection)
                    {
                        sb.AppendLine($"\t\t\t{identifier} = entity.{identifier}?.ToList(),");
                    }
                    else
                    {
                        sb.AppendLine($"\t\t\t{identifier} = entity.{identifier},");
                    }
                }
            }
            sb.AppendLine("\t\t};");
            sb.AppendLine("\t}");
        }


        private void AppendWarningDisables()
        {
            sb.AppendLine("#pragma warning disable CS8618"); // non-nullable not initialized
            sb.AppendLine("#pragma warning disable CS8601"); // possible null assignment
            sb.AppendLine("#pragma warning disable CS8603"); // possible null return
            sb.AppendLine("#pragma warning disable CS8604"); // possible null argument
            sb.AppendLine("#pragma warning disable CS8619"); // nullability mismatch
        }

        private void AppendWarningRestores()
        {
            sb.AppendLine("#pragma warning restore CS8618");
            sb.AppendLine("#pragma warning restore CS8601");
            sb.AppendLine("#pragma warning restore CS8603");
            sb.AppendLine("#pragma warning restore CS8604");
            sb.AppendLine("#pragma warning restore CS8619");
        }

    }



    private static string GetTypeName(ITypeSymbol type) => type.ToDisplayString(TypeFormat);

    private static bool IsCollectionType(IPropertySymbol property)
    {
        var type = property.Type;

        if (type.Name == "String") return false;

        if (type is INamedTypeSymbol namedType)
        {
            if (namedType.OriginalDefinition.Name is "IEnumerable"
                    or "IList"
                    or "ICollection"
                    or "IReadOnlyList"
                    or "IReadOnlyCollection"
                    && namedType.TypeArguments.Length == 1)
            {
                return true;
            }

            if (namedType.Name == "IEnumerable" && namedType.TypeArguments.Length == 1)
                return true;

            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.Name is "IEnumerable" or "ICollection" && iface.TypeArguments.Length == 1)
                    return true;
            }
        }

        return false;
    }

}
