using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EventMapperGenerator.SourceGenerators.ExtensionMethods;

internal static class EventMapperBuilderExtensions
{
    extension(SourceProductionContext context)
    {
        internal void BuildMapperSourceFile(GeneratedEventMapperData mapperData)
        {
            context.LogOnBuild($"AUTOGEN ----- Generating EventMapper for: {mapperData.EventTypeName}");

            StringBuilder sb = new();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");

            sb.AppendLine($"using {mapperData.EventNamespace};");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Text.Json.Nodes;");
            sb.AppendLine($"namespace {MappingProfile.MapperNamespace};");

            // Start class
            sb.AppendLine($"public static partial class {MappingProfile.MapperClassName}");
            sb.AppendLine("{");

            sb.AppendFromDbEvent(mapperData);
            sb.AppendToPayload(mapperData);

            // End class
            sb.AppendLine("}");

            context.AddSource(
                    $"{mapperData.EventTypeName}.{MappingProfile.MapperClassName}.g.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8)
                    );
            sb.Clear();
        }

        internal void BuildMainSourceFile(IEnumerable<string> eventTypeNames, IEnumerable<string> eventNamespaces)
        {
            context.LogOnBuild($"AUTOGEN ----- Generating Main FromDbEvent Switch Statement");

            StringBuilder sb = new();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");

            foreach (var ns in eventNamespaces)
                sb.AppendLine($"using {ns};");

            sb.AppendLine($"namespace {MappingProfile.MapperNamespace};");

            // Start class
            sb.AppendLine($"public static partial class {MappingProfile.MapperClassName}");
            sb.AppendLine("{");

            sb.AppendMainFromDbEvent(eventTypeNames);

            // End class
            sb.AppendLine("}");

            context.AddSource(
                    $"{MappingProfile.MainFileName}.{MappingProfile.MapperClassName}.g.cs",
                    SourceText.From(sb.ToString(), Encoding.UTF8)
                    );
            sb.Clear();
        }

        private void LogOnBuild(string message, bool asInfo = false)
        {
            context.ReportDiagnostic(
                    Diagnostic.Create(
                        new DiagnosticDescriptor(
                            "EVENT_MAPPER_GENERATOR_0001",
                            "Debug",
                            message,
                            "EventMapperGenerator",
                            asInfo ? DiagnosticSeverity.Info : DiagnosticSeverity.Warning,
                            isEnabledByDefault: true
                        ),
                        Location.None,
                        asInfo ? "Info" : "Warning")
                    );
        }

    }

    extension(StringBuilder sb)
    {
        internal void AppendFromDbEvent(GeneratedEventMapperData mapperData)
        {
            sb.AppendLine($"\tprivate static {mapperData.EventTypeName} "
                    + MappingProfile.GetFromDbEventMethodName(mapperData.EventTypeName)
                    + $"({MappingProfile.DbEventTypeName} dbEvent)");
            sb.AppendLine("\t{");
            sb.AppendLine($"\t\tvar payloadNode = JsonSerializer.Deserialize<JsonNode>(dbEvent.Payload)!;");

            sb.AppendLine($"\t\treturn new {mapperData.EventTypeName}(");

            var args = new List<string>();
            foreach (var prop in mapperData.BaseProps)
            {
                if (MappingProfile.SingleArgConstructorFields.Contains(prop.Name))
                    args.Add($"\t\t\t{prop.Name}: new(dbEvent.{prop.Name})");
                else
                    args.Add($"\t\t\t{prop.Name}: dbEvent.{prop.Name}");
            }

            foreach (var prop in mapperData.PayloadProps)
            {
                args.Add($"\t\t\t{prop.Name}: payloadNode[\"{prop.Name}\"]!.Deserialize<{prop.Type.ToDisplayString()}>()!");
            }

            sb.AppendJoin(",\n", args).AppendLine();

            sb.AppendLine("\t);");
            sb.AppendLine("\t}");
        }


        internal void AppendToPayload(GeneratedEventMapperData mapperData)
        {
            sb.AppendLine($"\tpublic static string ToPayload({mapperData.EventTypeName} e)");
            sb.AppendLine("\t{");
            sb.AppendLine("\t\tvar json = new JsonObject();");
            foreach (var prop in mapperData.PayloadProps)
            {
                sb.AppendLine($"\t\tjson[\"{prop.Name}\"] = JsonSerializer.SerializeToNode(e.{prop.Name});");
            }
            sb.AppendLine("\t\treturn json.ToString();");
            sb.AppendLine("\t}");
        }


        internal void AppendMainFromDbEvent(IEnumerable<string> eventTypeNames)
        {
            sb.AppendLine($"\tpublic static {MappingProfile.BaseEventTypeNameFriendly} "
                    + MappingProfile.MainFromDbEventMethodName
                    + $"({MappingProfile.DbEventTypeName} dbEvent)");

            sb.AppendLine($"\t\t=> dbEvent.EventType switch");
            sb.AppendLine("\t\t{");

            foreach (var et in eventTypeNames)
            {
                sb.AppendLine($"\t\t\t \"{et}\" => {MappingProfile.GetFromDbEventMethodName(et)}(dbEvent),");
            }

            sb.AppendLine("\t\t\t_ => throw new NotSupportedException($\"Unknown event type {dbEvent.EventType}\"),");
            sb.AppendLine("\t\t};");
        }
    }
}
