using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace DtoGenerator.SourceGenerators;

internal static class DtoBuilderExtensions
{
    public static void BuildDtoSourceFiles(this SourceProductionContext context,
            GeneratedDtoData dtoData)
    {
        context.LogOnBuild($"AUTOGEN ----- Generating Dto: {dtoData.DtoName}");

        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");

        // Add target namespace
        sb.AppendLine($"namespace {dtoData.TargetNamespace};");

        // Start class
        sb.AppendLine($"public partial class {dtoData.DtoName}");
        sb.AppendLine("{");

        sb.AppendProps(dtoData);
        sb.AppendFromMethod(dtoData);

        // Add closing braces
        sb.AppendLine("}");

        context.AddSource($"{dtoData.DtoName}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        sb.Clear();
    }


    private static void AppendProps(this StringBuilder sb,
            GeneratedDtoData dtoData)
    {
        sb.AppendLine("#pragma warning disable CS8618"); // CS8618: Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.

        foreach (var property in dtoData.Properties)
        {
            string type = property.Type.ToFullString();
            string identifier = property.Identifier.ValueText;

            if (dtoData.PropNameToMappedType.TryGetValue(identifier, out var mappedType))
            {
                if (IsCollectionType(type))
                {
                    type = $"List<{mappedType}>";
                }
                else
                {
                    type = mappedType;
                }
            }

            sb.AppendLine($"\tpublic {type} {identifier} {{get; set;}}");
        }

        sb.AppendLine("#pragma warning restore CS8618");
    }


    private static void AppendFromMethod(this StringBuilder sb,
            GeneratedDtoData dtoData)
    {
        sb.AppendLine($"\tpublic static {dtoData.DtoName} From({dtoData.TargetName} entity)");
        sb.AppendLine("\t{");
        sb.AppendLine("\t\tif (entity is null) return null!;");
        sb.AppendLine($"\t\treturn new {dtoData.DtoName} {{");
        foreach (var property in dtoData.Properties)
        {
            string identifier = property.Identifier.ValueText;
            string propertyType = property.Type.ToFullString();
            bool isCollectionType = IsCollectionType(propertyType);

            if (dtoData.PropNameToMappedType.TryGetValue(identifier, out var mappedType))
            {
                if (isCollectionType)
                    sb.AppendLine($"\t\t\t{identifier} = entity.{identifier}?.Select(x => {mappedType}.From(x!)).ToList()!,");
                else
                    sb.AppendLine($"\t\t\t{identifier} = {mappedType}.From(entity.{identifier}!),");
            }
            else
            {
                if (isCollectionType)
                    sb.AppendLine($"\t\t\t{identifier} = entity.{identifier}?.ToList()!,");
                else
                    sb.AppendLine($"\t\t\t{identifier} = entity.{identifier},");
            }
        }
        sb.AppendLine("\t\t};");
        sb.AppendLine("\t}");
    }

    private static bool IsCollectionType(string typeName)
    {
        return typeName.StartsWith("List<") ||
               typeName.StartsWith("IList<") ||
               typeName.StartsWith("ICollection<") ||
               typeName.StartsWith("IEnumerable<") ||
               typeName.StartsWith("IReadOnlyList<") ||
               typeName.StartsWith("IReadOnlyCollection<");
    }


    private static void LogOnBuild(this SourceProductionContext context,
            string message,
            bool asInfo = false)
    {
        context.ReportDiagnostic(
                Diagnostic.Create(
                    new DiagnosticDescriptor(
                        "DTOGEN001",
                        "Debug",
                        message,
                        "DtoGenerator",
                        asInfo ? DiagnosticSeverity.Info : DiagnosticSeverity.Warning,
                        isEnabledByDefault: true
                    ),
                    Location.None,
                    asInfo ? "Info" : "Warning")
                );
    }

}

